---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Mandatory Access Control configuration dependencies
#
########################################################################

- name: Run role dependency for mandatory access control
  ansible.builtin.include_role:
    name: "{{ cfg_mac_ssh_dep_item['role'] }}"
    allow_duplicates: true
    public: true
  when:
    - cfg_mac_ssh_dep_item['role'] not in ansible_role_names
      or cfg_mac_ssh_dep_item['dupes'] | default(false)
    - cfg_mac_ssh_dep_item['condition'] | default(true)
