---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure SELinux
#
########################################################################

- name: Enable SELinux and set to enforcing
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true

- name: Run the privilege escalation role to finish configuring SELinux
  ansible.builtin.include_role:
    name: "{{ priv_role_var }}"
    allow_duplicates: true
    public: true
  vars:
    priv_role_var: o0_o.host.privilege_escalation
  when:
    - priv_role_var not in ansible_parent_role_names | default([])
    - pre_vars['mac'] | default != 'selinux'
