---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the time zone on an SSH host
#
########################################################################

- name: Configure the time zone
  community.general.timezone:
    name: "{{ tz }}"
  become: true
