---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Sync time with localhost on an SSH host using the raw module
#
########################################################################

# Set the time in GMT without configuring the system to use GMT
- name: Configure time (raw)
  ansible.builtin.raw: >-
    {{ ansible_become_method }} TZ=GMT date {{ now(true, date_format) }}
  when: not ansible_check_mode

# Emulate check mode behavior
- name: The previous task would have resulted in a change (check mode)
  ansible.builtin.debug:
    msg: The time would be changed on the remote host.
  changed_when: true
  when: ansible_check_mode
