---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define the time on a RouterOS host
#
########################################################################

- name: Get time from the host (RouterOS)
  community.routeros.command:
    commands:
      - /put [/system clock get date]
      - /put [/system clock get time]
  changed_when: false
  register: ros_time_reg

- name: Define the current time on the remote host (RouterOS)
  ansible.builtin.set_fact:
    remote_datetime: "{{ datetime_var | to_datetime('%b/%d/%Y %H:%M:%S') }}"
  vars:
    datetime_var: >-
      {{ ros_time_reg['stdout_lines'][0][0] }}
      {{ ros_time_reg['stdout_lines'][1][0] }}
