---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define the time on an SSH host
#
########################################################################

- name: Define the date format as mmddHHMMccyy.ss
  ansible.builtin.set_fact:
    date_format: '%m%d%H%M%Y.%S'
  when: ansible_system | default(sys) | lower in ['linux', 'darwin']

- name: Define the date format as ccyymmddHHMM.ss
  ansible.builtin.set_fact:
    date_format: '%Y%m%d%H%M.%S'
  when: ansible_system | default(sys) | lower in ['freebsd', 'openbsd']

# -u flag = GMT/UTC
- name: Get time from the host (raw)
  ansible.builtin.raw: date -u '+%Y-%m-%d %H:%M:%S'
  register: remote_date_raw_reg
  changed_when: false
  when: use_raw

# Do not rely on ansible_date_time
- name: Get time from the host
  ansible.builtin.command:
    argv:
      - date
      - -u
      - +%Y-%m-%d %H:%M:%S
  register: remote_date_reg
  changed_when: false
  when: not use_raw

- name: Define the current time on the remote host
  ansible.builtin.set_fact:
    remote_datetime: >-
      {{  remote_date_reg['stdout_lines'][0]
          | default( remote_date_raw_reg['stdout_lines'][0] ) }}
