---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the time zone and sync time with localhost
#
########################################################################

- name: Scope time zone for general use
  ansible.builtin.set_fact:
    tz: "{{ tz }}"
  changed_when: pre_vars['tz'] | default != tz
  notify: update host inventory variables

- name: Run time definition SSH dependencies
  ansible.builtin.include_tasks: time_dep.yml
  loop: "{{ time_deps }}"
  loop_control:
    loop_var: time_dep_item

- name: Run tasks to define the time on the remote host
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='def_time_' ) }}"

- name: Run tasks to configure the time zone
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='cfg_time_zone_' ) }}"
  when: not use_raw

- name: Run tasks to sync time with localhost if necessary
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='cfg_time_',
                      suffix=tasks_file_suffix ) }}"
  vars:
    local_datetime_var: "{{ now(true, '%Y-%m-%d %H:%M:%S') }}" #GMT
    diff_var: "{{ ( ( local_datetime_var | to_datetime
                      - remote_datetime | to_datetime ).total_seconds() / 60 )
                  | abs }}"
  when: diff_var | int > time_sync_tolerance
