---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Dependencies for time configuration
#
########################################################################

- name: Run role dependency for time definition
  ansible.builtin.include_role:
    name: "{{ time_dep_item['role'] }}"
    allow_duplicates: true
    public: true
  when:
    - time_dep_item['role'] not in ansible_role_names
      or time_dep_item['dupes'] | default(false)
    - time_dep_item['condition'] | default(true)
