---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the SELinux context for the sudo user
#
########################################################################

- name: "Configure the user's SELinux context to {{ adm_seuser }}"
  community.general.selogin:
    login: "{{ user_var }}"
    seuser: "{{ adm_seuser }}"
    state: present
  register: user_selinux_context_change_reg
  become: "{{ become_var }}"
  notify: restore selinux contexts
