---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure the privilege escalation command
#
########################################################################

- name: Run privilege escalation command role dependencies
  ansible.builtin.include_tasks: cfg_priv_ssh_cmd_dep.yml
  loop: "{{ cfg_priv_ssh_cmd_deps }}"
  loop_control:
    loop_var: priv_cmd_dep_item

- name: Define platform-specific privilege escalation command variables
  ansible.builtin.include_vars:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'vars',
                      prefix='priv_',
                      skip=true ) }}"
  when: not use_raw

- name: Run tasks to configure the specific privilege escalation method
  ansible.builtin.include_tasks:
    cfg_priv_ssh_cmd_{{ ansible_become_method }}.yml
  when:
    - use_sw_mgmt
    - not use_raw

- name: Test the privilege escalation method with the intended user
  ansible.builtin.command:
    argv:
      - echo
      - 0
  become: true
  register: priv_user_test_reg
  changed_when: false
  failed_when:
    priv_user_test_reg['stdout_lines'][0] | default != '0'
    or priv_user_test_reg['rc'] != 0
  vars:
    ansible_user: "{{ priv_user }}"
  when: not use_raw
