---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Run Sudo role dependency
#
########################################################################

- name: Run the role dependencies for Sudo configuration
  ansible.builtin.include_role:
    name: "{{ sudo_dep_item['role'] }}"
    public: true
  when:
    - sudo_dep_item['role'] not in ansible_role_names
      or sudo_dep_item['dupes'] | default(false)
    - sudo_dep_item['condition'] | default(true)
