---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Attempt to configure the current become method for systems using SSH
#
########################################################################

- name: "Run tasks to Configure {{ ansible_become_method }}"
  ansible.builtin.include_tasks: >-
    cfg_become_ssh_cmd_{{ ansible_become_method }}{{ tasks_file_suffix }}.yml
  vars:
    become_var: "{{ ansible_user != 'root' }}"

# Adding a new Ansible user is not supported while limited to the raw
# module.
- name: "Run tasks to test {{ ansible_become_method }} with new user"
  ansible.builtin.include_tasks: test_become_ssh.yml
  vars:
    ansible_user: "{{ new_ansible_user_var }}"
  when: new_ansible_user_var is defined

- name: "Run tasks to test {{ ansible_become_method }} with current user"
  ansible.builtin.include_tasks: test_become_ssh{{ tasks_file_suffix }}.yml
  when: new_ansible_user_var is undefined

- name: "Scope {{ ansible_become_method }} for general use"
  ansible.builtin.set_fact:
    ansible_become_method: "{{ ansible_become_method }}"
