---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure doas as the privilege escalation method
#
########################################################################

- name: Configure user with passwordless doas privileges
  ansible.builtin.lineinfile:
    path: "{{ doas_cfg_path }}/{{ doas_cfg_file }}"
    regexp: " {{ priv_user | regex_escape }}$"
    line: "permit nopass {{ priv_user }}"
    state: present
    mode: "{{ doas_cfg_mode }}"
    create: true
    backup: true
    validate: "{{ doas_bin }} -C %s"
  become: "{{ not is_root_var }}"

# Remove unnecessary software
- name: Remove the sudo package
  ansible.builtin.package:
    name: sudo
    state: absent
  become: "{{ not is_root_var }}"
