---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure privilege escalation method for systems using SSH
#
########################################################################

- name: Run SSH privilege escalation dependencies
  ansible.builtin.include_tasks: cfg_priv_ssh_dep.yml
  when: priv_user != 'root'
  loop: "{{ cfg_priv_ssh_deps }}"
  loop_control:
    loop_var: priv_ssh_dep_item

- name: Test and define the privilege escalation method
  ansible.builtin.include_tasks: def_priv_ssh.yml
  vars:
    test_result_var: >-
      {{  test_priv_reg['stdout_lines'][0]
          | default( test_priv_root_reg['stdout_lines'][0] )
          | default
          | basename }}

- name: Run tasks to configure privilege escalation methods
  ansible.builtin.include_tasks: cfg_priv_ssh_cmd.yml
  when: ansible_become_method != ''
