---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Test the current become method
#
########################################################################

- name: Test the become method
  ansible.builtin.raw: "{{ ansible_become_method }} echo 0"
  register: test_become_reg
  changed_when: false
  failed_when: >-
    test_become_reg['rc'] > 0
    or test_become_reg['stdout_lines'][0] | default != '0'
