---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Rocky Linux software management defaults
#
########################################################################

# /etc/dnf/dnf.conf
rocky_dnf_cfg_default: {}
rocky_dnf_cfg_add: {}
rocky_dnf_cfg: >-
  {{  [ dnf_yum_cfg_common_default,
        dnf_yum_cfg_common_add,
        dnf_cfg_default,
        dnf_cfg_add,
        rocky_dnf_cfg_default,
        rocky_dnf_cfg_add ]
      | combine }}

# Default configuration for all DNF repositories in Rocky
rocky_dnf_repos_cfg_default:
  method: mirrorlist
  url: https://mirrors.rockylinux.org
  gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
rocky_dnf_repos_cfg_add: {}
rocky_dnf_repos_cfg: >-
  {{  [ repos_cfg,
        dnf_yum_repos_cfg_common_default,
        dnf_yum_repos_cfg_common_add,
        dnf_repos_cfg_default,
        dnf_repos_cfg_add,
        rocky_dnf_repos_cfg_default,
        rocky_dnf_repos_cfg_add ]
      | combine }}

# Individual default repositories
rocky_dnf_repo_baseos:
  name: Rocky Linux $releasever - BaseOS
  file: Rocky-BaseOS
  url_vars: 'arch=$basearch&repo=BaseOS-$releasever'
  url_path: /$contentdir/$releasever/BaseOS/$basearch/os/
  enabled: true
rocky_dnf_repo_appstream:
  name: Rocky Linux $releasever - AppStream
  file: Rocky-AppStream
  url_vars: 'arch=$basearch&repo=AppStream-$releasever'
  url_path: /$contentdir/$releasever/AppStream/$basearch/os/
  enabled: true
rocky_dnf_repo_extras:
  name: Rocky Linux $releasever - Extras
  file: Rocky-Extras
  url_vars: 'arch=$basearch&repo=extras-$releasever'
  url_path: /$contentdir/$releasever/extras/$basearch/os/
rocky_dnf_repo_ha:
  name: Rocky Linux $releasever - HighAvailability
  file: Rocky-HighAvailability
  url_vars: 'arch=$basearch&repo=HighAvailability-$releasever'
  url_path: /$contentdir/$releasever/HighAvailability/$basearch/os/
rocky_dnf_repo_nfv:
  name: Rocky Linux $releasever - NFV
  file: Rocky-NFV
  url_vars: 'arch=$basearch&repo=NFV-$releasever'
  url_path: /$contentdir/$releasever/nfv/$basearch/os/
rocky_dnf_repo_plus:
  name: Rocky Linux $releasever - Plus
  file: Rocky-Plus
  url_vars: 'arch=$basearch&repo=rockyplus-$releasever'
  url_path: /$contentdir/$releasever/plus/$basearch/os/
rocky_dnf_repo_powertools:
  name: Rocky Linux $releasever - PowerTools
  file: Rocky-PowerTools
  url_vars: 'arch=$basearch&repo=PowerTools-$releasever'
  url_path: /$contentdir/$releasever/PowerTools/$basearch/os/
rocky_dnf_repo_resilient_storage:
  name: Rocky Linux $releasever - ResilientStorage
  file: Rocky-ResilientStorage
  url_vars: 'arch=$basearch&repo=ResilientStorage-$releasever'
  url_path: /$contentdir/$releasever/ResilientStorage/$basearch/os/
rocky_dnf_repo_rt:
  name: Rocky Linux $releasever - Realtime
  file: Rocky-RT
  url_vars: 'arch=$basearch&repo=RT-$releasever'
  url_path: /$contentdir/$releasever/RT/$basearch/os/
# NOTE: If 'file' is not set, the key is used. The .repo extension is
# defined in vars/main/pkg_mgmt.yml. It should not be included here.

rocky_dnf_repos_default:
  baseos: >-
    {{ [rocky_dnf_repos_cfg, rocky_dnf_repo_baseos] | combine }}
  appstream: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_appstream] | combine }}
  extras: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_extras] | combine }}
  ha: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_ha] | combine }}
  nfv: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_nfv] | combine }}
  plus: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_plus] | combine }}
  powertools: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_powertools] | combine }}
  resilient-storage: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_resilient_storage] | combine }}
  rt: >-
    {{  [rocky_dnf_repos_cfg, rocky_dnf_repo_rt] | combine }}
rocky_dnf_repos_add: {}
rocky_dnf_repos: >-
  {{ [rocky_dnf_repos_default, rocky_dnf_repos_add] | combine }}
