---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Template the package manager's main configuration file
#
########################################################################

- name: Template the package manager's configuration file
  ansible.builtin.template:
    src: "{{ template_file_var }}"
    dest: "{{ cfg_file_var }}"
    mode: 0644
    owner: root
    group: "{{ root_grp }}"
    backup: true
  become: true

- name: Define a list of package managers with configuration changes
  ansible.builtin.set_fact:
    cfg_pkg_mgrs: >-
      {{ cfg_pkg_mgrs | default([]) | union( [pkg_mgr_var] ) }}
