---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure package management on an SSH host
#
########################################################################

- name: Run tasks to define the package manager
  ansible.builtin.include_tasks: def_pkg-mgr_ssh.yml
  vars:
    defaults_file_var: "defaults/{{ pkg_mgr_name_item }}.yml"
  when: lookup('ansible.builtin.fileglob', defaults_file_var) != []

- name: Run tasks to configure the package manager specifically
  ansible.builtin.include_tasks: "{{ tasks_file_var }}"
  vars:
    tasks_file_var: "tasks/\
      cfg_sw_ssh_pkg-mgr_{{ pkg_mgr_name_item }}{{ tasks_file_suffix }}.yml"
  when: lookup('ansible.builtin.fileglob', tasks_file_var) != []

- name: Run tasks to configure the package manager's main config file
  ansible.builtin.include_tasks:
    file: "cfg_sw_ssh_pkg-mgr_template{{ tasks_file_suffix }}.yml"
  vars:
    cfg_file_var: "{{ pkg_mgr_var['cfg_file'] }}"
    title_var: >-
      {{ pkg_mgr_name_pretty_var }} Package Manager Configuration
    pkg_mgr_cfg_var: >-
      {{  [ pkg_mgr_cfg[pkg_mgr_name_item] | default({}),
            dist_pkg_mgr_cfg[pkg_mgr_name_item] | default({}) ]
          | combine }}
    template_file_var: >-
      {{ pkg_mgr_name_item | regex_replace('^yum$', 'dnf') }}_cfg.j2
  when: cfg_file_var is defined

- name: Run tasks to template a single configuration file for all repositories
  ansible.builtin.include_tasks:
    file: "cfg_sw_ssh_pkg-mgr_template{{ tasks_file_suffix }}.yml"
  vars:
    cfg_file_var: "{{ pkg_mgr_var['repos_cfg_file'] }}"
    title_var: >-
      {{ pkg_mgr_name_pretty_var }} Repositories Configuration
    template_file_var: "{{ pkg_mgr_name_item }}_repos_cfg.j2"
  when: cfg_file_var is defined

- name: Repositories are configured in separate configuration files
  ansible.builtin.include_tasks:
    file: "cfg_sw_ssh_pkg-mgr_repos{{ tasks_file_suffix }}.yml"
  vars:
    repos_cfg_dir_var: "{{ pkg_mgr_var['repos_cfg_dir'] }}"
    ext_var: ".{{ pkg_mgr_var['repos_cfg_ext'] | default(omit, true) }}"
  when: repos_cfg_dir_var is defined
