---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Template the package manager's main configuration file
#
# Roughly emulate ansible.builtin.template using only raw commands.
#
########################################################################

- name: Get the contents of the configuration file
  ansible.builtin.raw: >-
    {{ ansible_become_method | default }}
    cat {{ cfg_file_var | quote }}
  register: cfg_file_reg
  changed_when: false
  failed_when: false

- name: The configuration file needs to be modified
  vars:
    cfg_template_var: >-
      {{  lookup( 'ansible.builtin.template',
                  "{{ template_file_var }}") }}
  when: cfg_file_reg['stdout_lines'] != cfg_template_var.splitlines()
  notify: "{{ notify_var }}"
  block:

    - name: The configuration file exists
      when: cfg_file_reg['rc'] == 0
      block:

          - name: Back up the configuration file
            ansible.builtin.raw: >-
              {{ ansible_become_method | default }}
              cp -a "{{ cfg_file_var | quote }}"
              {{ cfg_file_var | quote }}".$(date +%Y%m%d%H%M%S)~"
            when: not ansible_check_mode

          - name: >-
              The previous task would have resulted in a change (check mode)
            ansible.builtin.debug:
              msg: "{{ cfg_file_var }} would have been backed up."
            changed_when: true
            when: ansible_check_mode

    - name: Write the template to the configuration file
      ansible.builtin.raw: >-
        {{ ansible_become_method | default }} sh -c {{ cmd_var | quote }}
      vars:
        cmd_var: >-
          printf '%s' {{ cfg_template_var | quote }} >
          {{ cfg_file_var | quote }}
      when: not ansible_check_mode

    - name: The previous task would have resulted in a change (check mode)
      ansible.builtin.debug:
        msg: "{{ cfg_file_var }} would have been modified."
      changed_when: true
      when: ansible_check_mode

    - name: Define a list of package managers with configuration changes
      ansible.builtin.set_fact:
        cfg_pkg_mgrs: >-
          {{ cfg_pkg_mgrs | default([]) | union( [pkg_mgr_var] ) }}
