---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Install and/or update firmware on OpenBSD
#
########################################################################

- name: Check if firmware updates are available (OpenBSD)
  ansible.builtin.cmd: >-
    argv:
      - fw_update
      - -n
      - -p
      - "{{ fw_url }}/{{ ansible_distribution_version }}"
  register: obsd_fw_update_reg
  changed_when: false
  become: true

- name: Install and/or update firmware (OpenBSD)
  ansible.builtin.command:
    argv:
      - fw_update
      - -a
      - -p
      - "{{ fw_url }}/{{ ansible_distribution_version }}"
  become: true
  when: >-
    obsd_fw_update_reg['stdout_lines']
    | select('match', '^.*added none.*updated none.*$')
    == []
