---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define software defaults on an SSH host
#
########################################################################

- name: Define system software defaults
  ansible.builtin.include_vars:
    file: "defaults/{{ dist_var }}.yml"
    name: sys_sw_defaults
  vars:
    dist_var: >-
      {{  ansible_distribution
          | linux_os_release['ID']
          | default(sys)
          | lower }}

# Replicate defaults/main.yml behavior.
- name: Set system software variables to defaults if they are not defined
  ansible.builtin.set_fact:
    "{{ key_item }}": "{{ vars[key_item]
                          | default( sys_sw_defaults[key_item] ) }}"
  loop: "{{ sys_sw_defaults.keys() | list }}"
  loop_control:
    loop_var: key_item
