---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Initialize the package manager
#
########################################################################

- name: Initialize the package manager cache
  ansible.builtin.command:
    argv: "{{ [ pkg_mgr_item['init_cmd'] | default( pkg_mgr_item['cmd'] ),
                pkg_mgr_item['init_arg'] | default ]
              + pkg_mgr_item['init_opts'] | default([]) }}"
  register: clean_pm_cache_reg
  when: >-
    pkg_mgr_item['init_cmd'] is defined
    or pkg_mgr_item['init_arg'] is defined
    or pkg_mgr_item['init_opts'] is defined

- name: Set up GPG keys for the package manager
  ansible.builtin.command:
    argv: "{{ [ pkg_mgr_item['key_cmd'] | default( pkg_mgr_item['cmd'] ),
                pkg_mgr_item['key_arg'] | default ]
              + pkg_mgr_item['key_opts'] | default([]) | join(' ') }}"
  register: clean_pm_cache_reg
  when: >-
    pkg_mgr_item['key_cmd'] is defined
    or pkg_mgr_item['key_arg'] is defined
    or pkg_mgr_item['key_opts'] is defined

- name: Clean the package manager cache
  ansible.builtin.command:
    argv: "{{ [ pkg_mgr_item['clean_cmd'] | default( pkg_mgr_item['cmd'] ),
                pkg_mgr_item['clean_arg'] | default ]
              + pkg_mgr_item['clean_opts'] | default([]) | join(' ') }}"
  register: clean_pm_cache_reg
  when: >-
    pkg_mgr_item['clean_cmd'] is defined
    or pkg_mgr_item['clean_arg'] is defined
    or pkg_mgr_item['clean_opts'] is defined

- name: Update the package manager cache
  ansible.builtin.command:
    argv: "{{ [ pkg_mgr_item['update_cmd'] | default( pkg_mgr_item['cmd'] ),
                pkg_mgr_item['update_arg'] | default ]
              + pkg_mgr_item['update_opts'] | default([]) | join(' ') }}"
  register: up_pm_cache_reg
  failed_when: >-
    up_pm_cache_reg['rc'] not in  pkg_mgr_item['update_success_codes']
                                  | default([0])
  when: >-
    pkg_mgr_item['update_cmd'] is defined
    or pkg_mgr_item['update_arg'] is defined
    or pkg_mgr_item['update_opts'] is defined
