---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure Ansible's connection to the host
#
# If an initial connection attempt is unsuccessful, attempt to discover
# the correct parameters. Upon a successful connection, write
# connection-related Ansible variables to the host_vars file.
#
########################################################################

- name: Run the o0_o.inventory role
  ansible.builtin.include_role:
    name: o0_o.inventory
    allow_duplicates: false
    public: true

# Prevents some misbehavior.
- name: Define the Ansible host and connection
  ansible.builtin.set_fact:
    ansible_host: "{{ ansible_host }}"
    ansible_connection: "{{ ansible_connection }}"

- name: Install/update pip and ansible-pylibssh on localhost
  ansible.builtin.pip:
    name:
      - pip
      - ansible-pylibssh
    state: latest
  delegate_to: 127.0.0.1
  run_once: true
  when: use_libssh

- name: Run tasks to test the connection with existing configuration
  ansible.builtin.include_tasks: test_con.yml

- name: Run tasks to configure the connection if necessary
  ansible.builtin.include_tasks: cfg_con.yml
  when: not use_con
