---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Test RouterOS connection
#
########################################################################

# This disables formatting and sets display width to 1024 to avoid line
# breaks in output.
- name: Add +cet1024w suffix to Ansible user (RouterOS)
  ansible.builtin.set_fact:
    ansible_user: "{{ ansible_user }}+cet1024w"
  when: ansible_user | regex_search('\+cet1024w$') is none

- name: Test the connection (RouterOS) [YUBIKEY PRESS]
  community.routeros.command:
    commands:
      - /put [/system identity get value-name=name]
  register: test_con_reg
  changed_when: false
  until: test_con_reg['stdout_lines'][0][0] | default('') != ''
  ignore_errors: true
  ignore_unreachable: true
  timeout: "{{ con_timeout }}"
  retries: "{{ con_retries }}"
  when:
    test_con_reg['unreachable'] | default(false)
    or test_con_reg['failed'] | default(true)

# Avoid running this in test_con.yml to save time and because the
# approach of use vars[var_item] will not work if the value is jinja,
# as in the case of the default value of net_ssh_method.
- name: Scope functional network connection variables for general use
  ansible.builtin.set_fact:
    ansible_network_os: "{{ ansible_network_os }}"
    ansible_network_cli_ssh_type: "{{ ansible_network_cli_ssh_type }}"
  changed_when:
    pre_vars['ansible_network_os'] | default != ansible_network_os
    or  pre_vars['ansible_network_cli_ssh_type'] | default
        != ansible_network_cli_ssh_type
  when:
    - not test_con_reg is failed
    - not test_con_reg is unreachable
  notify: update host inventory variables
