---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Test connection with different operating systems
#
########################################################################

- name: Run tasks to test the connection
  ansible.builtin.include_tasks: test_con.yml

- name: Run tasks to test the connection (RouterOS)
  ansible.builtin.include_tasks: test_con.yml
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.network.routeros
    ansible_network_cli_ssh_type: "{{ net_ssh_method }}"
  when:
    - not use_con
    - net_ssh_method in ['libssh', 'paramiko']
