---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Test connections with different users
#
########################################################################

- name: Define the Ansible user candidate
  ansible.builtin.set_fact:
    ansible_user: "{{ adm_item }}"
  when: not use_con

- name: "Test {{ ansible_user }}@{{ ansible_host }}"
  ansible.builtin.include_tasks: test_con_oses.yml
  when: not use_con
