---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Test connection
#
########################################################################

# This will run either test_con_ssh.yml or test_con_routeros.yml
- name: Run tasks to test the connection
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='test_con_' ) }}"

# Do not accept connections to localhost on default port 22 (prevents
# accidentally targeting localhost when configuring virtual hosts on
# local NAT). To target localhost, use the local connection type or
# SSH with an ansible_host value other than 127.0.0.1.
- name: Use the connection if it was successful
  ansible.builtin.set_fact:
    use_con: >-
      {{  not ( ansible_host == '127.0.0.1'
                and ansible_port | default('22') | string == '22' )
          and test_con_reg is not failed
          and test_con_reg is not unreachable }}

- name: Scope functional connection variables for general use
  ansible.builtin.set_fact:
    ansible_host: "{{ ansible_host }}"
    ansible_connection: "{{ ansible_connection }}"
    ansible_port: "{{ ansible_port | default(omit) }}"
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file
                                      | default(omit) }}"
    ansible_user: "{{ ansible_user }}"
    ansible_network_os: "{{ ansible_network_os | default(omit) }}"
    ansible_network_cli_ssh_type: "{{ ansible_network_cli_ssh_type
                                      | default(omit) }}"
  changed_when:
    pre_vars['ansible_host'] | default
    !=  vars['ansible_host'] | default
    or  pre_vars['ansible_connection'] | default
        !=  vars['ansible_connection'] | default
    or  pre_vars['ansible_port'] | default
        !=  vars['ansible_port'] | default
    or  pre_vars['ansible_ssh_private_key_file'] | default
        !=  vars['ansible_ssh_private_key_file'] | default
    or  pre_vars['ansible_user'] | default
        !=  vars['ansible_user'] | default
    or  pre_vars['ansible_network_os'] | default
        !=  vars['ansible_network_os'] | default
    or  pre_vars['ansible_network_cli_ssh_type'] | default
        !=  vars['ansible_network_cli_ssh_type'] | default
  when: use_con
  notify: update host inventory variables
