---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Time defaults
#
########################################################################

time_sync: false
time_sync_tolerance: 5 #minutes

# Dependencies
time_deps:
  - role: o0_o.host.facts
    condition: "{{ use_raw is undefined }}"
  - role: o0_o.host.privilege_escalation
