---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Time defaults
#
########################################################################

# Use localhost's time zone by default.
tz: "{{ lookup('ansible.builtin.pipe', 'date +%Z')
        | regex_replace('UTC', 'GMT') }}"

time_sync_tolerance: 5 #minutes

# Dependencies
time_deps:
  - role: o0_o.host.privilege_escalation
