---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Python interpreter defaults
#
########################################################################

# Dependencies
def_python_ssh_raw_deps:
  - role: o0_o.host.facts
install_python_ssh_raw_deps:
  - role: o0_o.host.privilege_escalation
  - role: o0_o.host.software_management
    dupes: true
    condition: "{{ not use_sw_mgmt | default(false) }}"
