---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define a dictionary of groups currently on the host
#
########################################################################

- name: Use getent to gather group information
  ansible.builtin.getent:
    database: group
  become: true

- name: Define a dictionary of current groups
  ansible.builtin.set_fact:
    current_grps: "{{ current_grps | combine(grp_var, recursive=true) }}"
  vars:
    grp_var: "{{ { grp_name_item: grp_val_var } }}"
    grp_val_var:
      gid: "{{ getent_group[grp_name_item][1] }}"
      members: "{{  getent_group[grp_name_item][2]
                    | default('')
                    | split(' ') }}"
  loop: "{{ getent_group.keys() | list }}"
  loop_control:
    loop_var: grp_name_item
