---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# User definition dependencies
#
########################################################################

- name: Run role dependency for users
  ansible.builtin.include_role:
    name: "{{ def_users_dep_item['role'] }}"
    allow_duplicates: true
    public: true
  when:
    - def_users_dep_item['role'] not in ansible_role_names
      or def_users_dep_item['dupes'] | default(false)
    - def_users_dep_item['condition'] | default(true)
