---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Define a list of non-system users currently on the host
#
########################################################################

- name: Reset current user list and groups dictionary
  ansible.builtin.set_fact:
    current_user_list: []
    current_grps: {}

- name: Run tasks to define a list of current groups
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='def_grps_current_' ) }}"
  when: ansible_network_os | default != 'community.network.routeros'

- name: Run tasks to define a list of current users
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='def_users_current_' ) }}"

- name: Run tasks to finish defining each current user including group
    membership and SSH credentials
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='def_user_current_' ) }}"
  vars:
    user_var: "{{ current_user_list[user_index] }}"
  # Use indexed loop for optimal, parallel execution
  loop: "{{ range( 0, current_user_list | length ) | list }}"
  loop_control:
    loop_var: user_index
