---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Delete a user
#
########################################################################

- name: Delete extra users or users marked for deletion
  ansible.builtin.user:
    name: "{{ del_user_name_item | default(del_user_name_var) }}"
    state: absent
    remove: true
    force: true
  become: true
  register: del_user_reg

- name: Record user configuration change
  ansible.builtin.set_fact:
    user_change: true
  when: del_user_reg is changed
