---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Delete a user on a RouterOS host
#
########################################################################

- name: Delete extra users or users marked for deletion (RouterOS)
  community.routeros.command:
    commands:
      - "/user remove {{ del_user_name_item | default(del_user_name_var) }}"
  register: ros_del_user_reg

- name: Record user configuration change
  ansible.builtin.set_fact:
    user_change: true
  when: ros_del_user_reg is changed
