---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Handlers for manadatory access control
#
########################################################################

- name: restore selinux contexts
  ansible.builtin.include_tasks: restore_selinux_contexts.yml
