---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Facts defaults
#
########################################################################

bad_serials:
  - ''
  - 0

# Replicate ssh-copy-id behavior using most recent key first
ssh_pub_key_local_file: >-
  {{  lookup('ansible.builtin.pipe', 'ls -Lt1 ~/.ssh/*.pub').splitlines()
      | first }}
ssh_pub_key: "{{ lookup( 'ansible.builtin.file', ssh_pub_key_local_file) }}"
