---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Facts defaults
#
########################################################################

# Unacceptable values for ansible_product_serial
bad_serials:
  - ''
  - 0

# Replicate ssh-copy-id behavior using most recent key first
ssh_pub_key_local_file: >-
  {{  lookup('ansible.builtin.pipe', 'ls -Lt1 ~/.ssh/*.pub').splitlines()
      | first }}
local_ssh_pub_key: >-
  {{ lookup( 'ansible.builtin.file', ssh_pub_key_local_file) }}

# Rely on the raw module by default
use_raw: "{{ ansible_connection == 'ssh' }}"
tasks_file_suffix: "{{ use_raw | ternary('_raw', '') }}"
