---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Mandatory access control variables
#
########################################################################

# Dependencies
cfg_mac_ssh_deps:
  - role: o0_o.host.software_management
    dupes: true
    condition: "{{ not use_sw_mgmt | default(false) }}"
