---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Mandatory access control variables
#
########################################################################

# Dependencies
cfg_mac_ssh_deps:
  - o0_o.host.software_management
