---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Configure repositories on an SSH host using the raw module
#
# These tasks will configure repositories in separate configuration
# files as in the case of DNF.
#
########################################################################

- name: >-
    List configuration files currently in repositories configuration directory
    (raw)
  ansible.builtin.raw: >-
    {{ ansible_become_method }} ls -1
    {{ repos_cfg_dir_var | quote }}
  register: repo_cfg_files_reg
  changed_when: false

# This is necessary when repository configuration files are idenfitied
# by file extension.
- name: There are extraneous repository configuration files
  when:
    - extra_files_var != []
    - ext_var != ''
  block:

    - name: Backup extraneous repository configuration files (raw)
      ansible.builtin.raw: >-
        {{ ansible_become_method }} mv
        {{ extra_file_path_var | quote }}
        {{ extra_file_path_var | quote }}".$(date +%Y%m%d%H%M%S)~"
      when: not ansible_check_mode
      loop: "{{ extra_files_var }}"
      loop_control:
        loop_var: extra_file_item

    - name: The previous task would have resulted in a change (check mode)
      ansible.builtin.debug:
        msg: >-
          {{ extra_files_var | length }} repository configuration files
          would have been renamed.
      changed_when: true
      when: ansible_check_mode

- name: Run tasks to template the each repository config file (raw)
  ansible.builtin.include_tasks: cfg_sw_ssh_pkg-mgr_template_raw.yml
  # Use indexed loop for optimal, parallel execution
  loop: "{{ range( 0, repo_list | length ) | list }}"
  loop_control:
    loop_var: repo_index
