---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Run package manager commands
#
# See vars/main/pkg_mgmt.yml
#
########################################################################

- name: "Run the package manager {{ cmd_name_item }} command"
  ansible.builtin.command:
    argv: "{{ cmd_var }}"
  environment: "{{ pkg_mgr_var['env'] | default({}) }}"
  register: pkg_mgr_cmd_reg
  become: true
  failed_when: pkg_mgr_cmd_reg['rc'] not in success_codes_var
  when: pkg_mgr_var[cmd_name_item] is defined
