---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Gather facts on a Linux host
#
########################################################################

- name: Get the systemd version (Linux)
  ansible.builtin.command:
    argv:
      - systemctl
      - --version
  register: sysd_vers_reg
  changed_when: false

- name: Define the systemd version (Linux)
  ansible.builtin.set_fact:
    sysd_vers: "{{  sysd_vers_reg['stdout_lines'][0]
                    | split(' ')
                    | last
                    | regex_replace('[)(]', '') }}"

- name: Define the systemd major and minor versions (Linux)
  ansible.builtin.set_fact:
    sysd_maj_vers: "{{ sysd_vers | split('.') | first }}"
    sysd_min_vers: "{{ sysd_vers | split('.') | last }}"
