---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Gather facts
#
########################################################################

- name: BEGIN HOST FACTS ROLE
  ansible.builtin.set_fact:
    role_call_ident: "{{ ident_var }}"
    role_call: "{{ role_call | default([]) + line_var }}"
  vars:
    ident_var: "{{ role_call_ident | default(-1) | int + 1 }}"
    line_var:
      - "{{ ( '  ' * ident_var | int ) | string + ansible_role_name }}"

- name: Define the public SSH key
  ansible.builtin.set_fact:
    ssh_pub_key:
      type: "{{ key_var | split(' ') | first | split('-') | last }}"
      pub: "{{ ( key_var | split(' ') )[1] }}"
  vars:
    ansible_pub_key_var: >-
      {{  lookup( 'ansible.builtin.pipe',
                  'ssh-keygen -y -f ' + ansible_ssh_private_key_file ) }}
    key_var: "{{  ( ansible_ssh_private_key_file is defined )
                  | ternary(ansible_pub_key_var, local_ssh_pub_key) }}"

- name: Run tasks to determine if the raw module should be used
  ansible.builtin.include_tasks: def_raw.yml

- name: Run tasks to gather facts based on connection type or network OS
  ansible.builtin.include_tasks:
    file: "{{ lookup( 'o0_o.host.first_found_by_host_attributes',
                      'tasks',
                      prefix='gather_facts_',
                      suffix=tasks_file_suffix ) }}"

- name: Define the OS name
  ansible.builtin.set_fact:
    os_name: "{{  ansible_distribution
                  | default( linux_os_release['ID'] )
                  | default(sys)
                  | default(ansible_network_os)
                  | split('.')
                  | last
                  | lower
                  | regex_replace('^arch$', 'archlinux')
                  | regex_replace('macosx', 'darwin') }}"

# See vars/main.yml for root_grps dictionary
- name: Define the root group based on the system
  ansible.builtin.set_fact:
    root_grp: "{{ root_grp_var }}"
  vars:
    root_grp_var: "{{ root_grps[ ansible_system | default(sys) | lower ] }}"
  when: root_grp_var is defined

- name: END HOST FACTS ROLE
  ansible.builtin.set_fact:
    role_call_ident: "{{ role_call_ident | int - 1 }}"
