---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Package manager variables
#
########################################################################

tasks_file_suffix: "{{  ( ansible_facts | default({}) == {} )
                        | ternary('_raw', '') }}"

pkg_mgrs:

  aptitude:
    cmd: apt-get
    cfg_file: /etc/apt/apt.conf.d/90overrides
    repos_cfg_file: /etc/apt/sources.list
    clean_arg: clean
    update_arg: update
    update_opts:
      - --assume-yes
      - --quiet
    install_arg: install
    install_opts:
      - --assume-yes
      - --quiet
    upgrade_arg: upgrade
    upgrade_opts:
      - --assume-yes
      - --quiet

  homebrew:
    cmd: brew
    clean_arg: cleanup
    clean_opts:
      - -s
    update_arg: update
    install_arg: install
    upgrade_arg: upgrade

  dnf:
    cmd: dnf
    cfg_file: /etc/dnf/dnf.conf
    repos_cfg_dir: /etc/yum.repos.d/
    repos_cfg_ext: repo
    clean_arg: clean
    clean_opts:
      - all
    update_arg: check-update
    update_opts:
      - --assumeyes
      - --debuglevel=1
    update_success_codes:
      - 0
      - 100 #exits 100 if updates are available
    install_arg: install
    install_opts:
      - --assumeyes
    upgrade_arg: update
    upgrade_opts:
      - --assumeyes

  freebsd_pkg:
    cmd: pkg
    cfg_file: /usr/local/etc/pkg.conf
    repos_cfg_dir: /usr/local/etc/pkg/repos
    repos_cfg_ext: conf
    clean_arg: clean
    clean_opts:
      - -a
    update_arg: update
    update_opts:
      - -f
    install_arg: install
    install_opts:
      - --yes
    upgrade_arg: upgrade
    upgrade_opts:
      - --yes

  openbsd_pkg:
    cmd: pkg_add
    repos_cfg_file: /etc/installurl
    clean_cmd: pkg_check
    clean_opts:
      - -F
      - -f
      - -I
    update_opts:
      - -s
      - -I
      - -u
    install_opts:
      - -z
    upgrade_opts:
      - -u

  pacman:
    cmd: pacman
    init_cmd: pacman-key
    init_opts:
      - --init
    key_cmd: pacman-key
    key_opts:
      - --populate
    cfg_file: /etc/pacman.conf
    clean_opts:
      - --sync
      - --clean
      - --noconfirm
    update_opts:
      - --sync
      - --refresh
      - --refresh
    install_opts:
      - --sync
      - --noconfirm
    upgrade_opts:
      - --sysupgrade
      - --noconfirm

  yum:
    cmd: yum
    cfg_file: /etc/yum.conf
    repos_cfg_dir: /etc/yum.repos.d/
    repos_cfg_ext: repo
    clean_arg: clean
    clean_opts:
      - all
    update_arg: check-update
    update_opts:
      - --assumeyes
      - --debuglevel=1
    update_success_codes:
      - 0
      - 100 #exits 100 if updates are available
    install_arg: install
    install_opts:
      - --assumeyes
    upgrade_arg: update
    upgrade_opts:
      - --assumeyes
