---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Dependencies for Python interpreter definitions
#
########################################################################

- name: Run role dependency for Python interpreter definition
  ansible.builtin.include_role:
    name: "{{ def_python_ssh_raw_dep_item['role'] }}"
    allow_duplicates: true
    public: true
  when:
    - def_python_ssh_raw_dep_item['role'] not in ansible_role_names
      or def_python_ssh_raw_dep_item['dupes'] | default(false)
    - def_python_ssh_raw_dep_item['condition'] | default(true)
