---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Dependencies for Python interpreter definitions
#
########################################################################

- name: Run role dependencies for Python interpreter definition
  ansible.builtin.include_role:
    name: "{{ def_python_ssh_raw_dep_item }}"
    public: true
  when: def_python_ssh_raw_dep_item not in ansible_role_names
