---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Dependencies for Python interpreter installation
#
########################################################################

- name: Run role dependencies for Python interpreter installation
  ansible.builtin.include_role:
    name: "{{ install_python_ssh_raw_dep_item }}"
    public: true
  when: >-
    install_python_ssh_raw_dep_item not in ansible_role_names
    or  ( install_python_ssh_raw_dep_item == 'o0_o.host.software_management'
          and use_sw_mgmt | default(false) == false )
