---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Dependencies for Python interpreter installation
#
########################################################################

- name: Run role dependency for Python interpreter installation
  ansible.builtin.include_role:
    name: "{{ install_python_ssh_raw_dep_item['role'] }}"
    public: true
  when:
    - install_python_ssh_raw_dep_item['role'] not in ansible_role_names
      or install_python_ssh_raw_dep_item['dupes'] | default(false)
    - install_python_ssh_raw_dep_item['condition'] | default(true)
