---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Discover and if necessary, install a Python interpreter
#
########################################################################

# Skip on network systems where Python interpreter is not applicable.
- name: Run tasks to configure the Python interpreter
  ansible.builtin.include_tasks: cfg_python_ssh.yml
  when: ansible_connection == 'ssh'
