---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Connection defaults
#
########################################################################

use_con: false
con_retries: 2
con_timeout: 12

# Cannot use libssh until this is resolved:
# https://github.com/ansible-collections/community.routeros/issues/132
net_ssh_method: paramiko

default_adms:
  - root
  - pi
  - vagrant
  - admin
  - ubnt
