---
# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
#
# Facts handlers
#
########################################################################

- name: update facts
  ansible.builtin.include_tasks: main.yml
